### ISSUE TITLE
CBS TECO demo - video script

### ISSUE THREAD

**Issue by NMichas** [OpenWIS/djibouti#17]
Hi and welcome to OpenWIS 2.0 proof of concept. Let's walk you through some work we have been doing over the last couple of months.

----

So, here is the current OpenWIS we all know and love.
People are searching for weather products all over the world. Data producers are producing data, and GISCs harvest and index data.
but... real-time access to data is limited.

----

So we asked... how can we make it better?

----

We'll tell you a story... but let's first introduce our heroes!
Here's Mouktar who runs a small server in a remote location.
He's not a computer expert, so he installs a Local Data Sharing Hub, using a fully automated procedure that only takes a few minutes.

----

Say hello to Omar.
Omar is pretty good with computers and wants to distribute Mouktar's data.
Omar installs a Regional Data Sharing Hub using a fully automated procedure that only takes a few minutes.

----

Hey Vicky!
Vicky works for a large association and wants to provide a comprehensive, curated list of  weather-related products and data.
Vicky install an AWISC - the Authoritative WIS Catalogue.

----

Here's Mohamed and Dave.
Mohamed is working outdoors and wants to google today's weather conditions.
Dave is a seasoned meteorologist.
Ohh, it seems we forgot Mariam! Mariam is working on a weather prediction model for which she needs real-time access to Mouktar's data.

----

So, these are our heroes.
Mouktar, running the Local Data Sharing Hub.
Omar, running the Regional Data Sharing hub.
Vicky, running the Authoritative WIS catalogue.
Mohamed and Dave  searching for information
and Mariam wanting real-time access to data.

---

So here's how the system works:
As soon as Mouktar pushes data to its local system, it is automatically transmitted in real-time to Omar's system.
Vicky's system is indexing Mouktar's data too, to update its local list of curated entries.
Google is also indexing Mouktar's data.

---

When Mohamed is looking for data, he can use google like he is used to.
Dave, wants and expert search interface, one that google cant' provide, so he is using AWISC. 
Mariam can subscribe to the RDSH to get notifications as soon as new data is available.

**Comment by woollattd** [comment]
My thoughts on changes to the intro section (changes in Bold):

Hi and welcome to **the OpenWIS Association's** proof of concept. Let's walk you through some work we have been doing over the last couple of months.

So, here is the current **WIS 1.0 concept** we all know and love.
People are searching for weather products all over the world. Data producers are producing data, and GISCs harvest and index data.
but... real-time access to data is limited.

So we asked **ourselves**... how can we make it better **for WIS 2.0**?

**Comment by solson-nws** [comment]
[Narrative for PoC Script with actions.docx](https://github.com/OpenWIS/djibouti/files/1720166/Narrative.for.PoC.Script.with.actions.docx)

**Comment by solson-nws** [comment]
Added a narrative for CBS Demo.  Jeremy and others, please feel free to review and comment.

Thanks!

Steve

**Comment by solson-nws** [comment]
Please comment by next thursday to allow enough time to redo the video before CBS TECO

Thanks!

Steve

**Comment by 6a6d74** [comment]
@solson-nws ... will do my best to review on the requested timescale

**Comment by rogers492** [comment]
The TECO slot is 30 mins. We are planning for:
5 mins **video**
15 mins **demo**
10 mins **Q&A**

**Comment by rogers492** [comment]
Video: https://www.powtoon.com/online-presentation/grcPPrt8sh0/?mode=movie

**Comment by 6a6d74** [comment]
Hi - having seen what ED have developed for the PoC, I have developed a narrative that walks us through all the important parts of the systems ...

See the attached PDF. I hope you can read my handwriting!

[OpenWIS2.0 demonstration script for CBS TECO.pdf](https://github.com/OpenWIS/djibouti/files/1797892/OpenWIS2.0.demonstration.script.for.CBS.TECO.pdf)

(note: I am on vacation during the early part of next week, so may be slow in answering any emails for clarification. If it's urgent, please get Paul to call me on the phone)

**Comment by tg4444** [comment]
Hi all,

Here's a little feedback on Jeremy's pdf.

1. We will provide you with the configuration (URLs, names, etc.) required for the integration of the Gaul LDSH with AWISC and RDSH, by Thursday the 14th.
2. Step/Section 8: There is no QR-code that takes you to the page where you subscribe to the dataset. The subscription URI exists in textual form on the "human-radable webpage".
3. Step/Section 9: After a new dataset is added to the LDSH, it will be necesssary to use the "Index now" button of the AWISC, in order to get information from the LDSH immediately, and not have to wait for the scheduled job to execute.
4. Step/Section 10: Please note that the channel will be created only when the first piece of data/notification has been disseminated, because it is created on-the-fly.
5. Step/Section 11: We intended to provide a QR-code that could be used to automatically subscribe to the channel, but we could not find a mobile MQTT client that could function by direct/indirect scanning of a QR-code, so we scrapped the idea. As a result, the URL will need to be entered manually into the mobile app. (Please note that @dimipapadeas  has provided a selection of MQTT clients that could be used, here: https://github.com/OpenWIS/djibouti/issues/18)
6. Step/Section 12: We did not manage to find a way to provide a browser-based FTP file upload, so an actual FTP client will have to be used. We can provide you with options for specific O/S's if you wish.

**Comment by rogers492** [comment]
One more thought. 

Everything is browser based (LDSH, RDSH, AWISC ... and even the FTP client) so I can run each one of those bits myself - or with help from Rémy and others actually in Geneva. 

I can even use different browsers (edge, chrome, Firefox etc) to make it look even more distributed...

The only bit we won’t have software for will be the MQTT client. 

Suggest that Nassos (or one the ED team) play the role of Mariam via WebEx ...

They can share their screen and show the MQTT client receiving the data. 

I think this would improve the demo anyway, because Mariam would be a remote user - like in real life. 

See what the ED guys think?

Also- if we need a plug in for the FTP client in the browser, I need to know ahead of time so that I can get it installed. 

Jeremy

**Comment by dimipapadeas** [comment]
We will be happy to join through Webex and play the Mariam role. Just please provide us with the script/use-cases you want us to act.

Concerning the browser FTP plugin, the best we could come find is a Chrome App, called **sFTP**.
The bad news with it is that it is not actually integrated within chrome, but starts like an external application, much like Filezilla.
Also, to launch it, you need to either do it from your O/S start menu, or do the following:

1. Open Chrome.
2. In the address bar at the top, type chrome://apps.
3. Press Enter.
4. Click the app you want to open.

**Comment by solson-nws** [comment]
Another thought would be to have Mark Oberfield play the role of Mariam,
since he created the weather data for the 4 locations.

Steve

**Comment by rogers492** [comment]
Do we know what time of day the demo session is scheduled for? We probably want someone playing Mariam who was going to be awake anyway - so afternoon in Geneva would be OK for Mark, anytime would be OK for europeans, most times would be tricky for Korea and Australia.

**Comment by rogers492** [comment]
I think the demo session begins at 27/3/2018 14:00 Geneva time, or later in the afternoon.

**Comment by rogers492** [comment]
@6a6d74 George has added some useful notes above about your narrative. When discussing it, we also thought you might like to mention that Google does not crawl/index a NEW data set instantaneously. However, if you have subscribed to a data set, new data is notified/sent immediately.

**Comment by NMichas** [comment]
Please check the attached consolidated version having the gaps filled-in. If someone could address my comments within the document we may consider the script finalised.
[video-script.docx](https://github.com/OpenWIS/djibouti/files/1807794/video-script.docx)

**Comment by wqu-bom** [comment]
In video-script.docx, Nassos ask to confirm whether to inlcude "some goals of this Proof of Concept study and how they could fulfill WIS 2.0 objectives". I think this is necessary, as we need to introduce or reinforce (if already introduced eleswhere) the main ideas of WIS2.0, at least those ideas that this PoC tried to explore. The first goal is ok to me and relevant to WIS2.0. I am not sure about the second and third dot points (the fourth one is the repeat of third one) and whether they are relevant to the PoC and in what way. By look at the vedio, this PoC is mainly about "to increase the discoverability and accessibility of authoritative weather, water and climate data", although WIS2.0 may involve other innovations. I suggest to restrict to the first goal, which could save a couple of slides.

**Comment by NMichas** [comment]
# Final version proposal

Hi and welcome to OpenWIS Association's proof of concept. Let's walk you through some work we have been doing over the last couple of months.

So, here is the current OpenWIS 1.0 concept we all know and love.
People are searching for weather products all over the world. Data producers are producing data, and GISCs harvest and index data.
but... real-time access to data is limited. And for that matter, so is the ability to discover this data publicly

So we asked ourselves... how can we make it better for WIS 2.0?

Let’s start with some goals of this Proof of Concept study and how they could fulfill WIS 2.0 objectives:  
- The first goal is to increase the discoverability and accessibility of authoritative weather, water and climate data.
- The second goal is to show real-time data transfer using commodity open-standard software instead of the WMO Global Telecommunication System.

Now let's introduce the cast and their roles!

First, there’s John who wants to publish datasets to the web from a remote location.
He's not a computer expert, so he installs a Local Data Sharing Hub, using a fully automated procedure that only takes a few minutes.  Think of a Local Data Sharing Hub as a small piece of software allowing anyone to publish datasets on the Web.

Say hello to Omar.
Omar wants to distribute John's data, he installs a Regional Data Sharing Hub using a fully automated procedure that only takes a few minutes.  A Regional Data Sharing Hub allows end-users to receive real-time notifications about data updates from Local Data Sharing Hubs.

Now say hello to Vicky!
Vicky works for a large association and wants to provide a comprehensive, curated list of weather-related products and data.
Vicky installs an AWISC - An Authoritative WIS Catalogue.  An Authoritative WIS Catalogue is designed to provide a curated view of all datasets registered in WIS.

Next, meet Mohamed and Dave.
Mohamed is working outdoors and wants to google today's weather conditions. 
Dave is a seasoned meteorologist.  Dave wants access to an expert search interface and a curated list of WIS datasets.

Oh, it seems we forgot Mariam! Mariam is working on a weather prediction model for which she needs real-time access to John's data.

So, this is our cast:
John, running the Local Data Sharing Hub.
Omar, running the Regional Data Sharing hub.
Vicky, running the Authoritative WIS catalogue.
Mohamed and Dave searching for information
and Mariam wanting real-time access to data.

So here's how the Proof of Concept system works:
 As soon as John pushes data to its local system, it is automatically transmitted in real-time to Omar's system.  Vicky's system is indexing John's data too, to update its local list of curated entries. Google is also indexing John's data.

When Mohamed is looking for data, he can use google like he is used to.
Dave, wants and expert search interface, one that google cant' provide, so he is using AWISC.  AWISC provides a customised user interface to perform weather-related searches.
Mariam can subscribe to the RDSH to get notifications as soon as new data is available.

**Comment by 6a6d74** [comment]
Hi - I've created some slides to run through during the demo. There are some bits (the text in red) that need to be finalized e.g. the subscribtion URL ...

Also, I think that Paul took a few notes when we met on Friday about small amendments in the demonstration. I'm not sure if I captured all these ... worth cross-referencing with Paul.

[openwis-wis2-demo-cbsteco-ii.pptx](https://github.com/OpenWIS/djibouti/files/1826042/openwis-wis2-demo-cbsteco-ii.pptx)

**Comment by rogers492** [comment]
Notes for the demo (JT narrative):
1. Mention that the LDSH can be an NC or DCPC etc, to explain the new vocab in WIS 1.0 terms.
2. Explain the advantages of having an LDSH - can do local searches, ease of pub to web etc.
3. Also explain the value of the RDSH and AWISC.
4. Merge section section 10 and 12 because the channel only appears when you push data. Make the point that the channel is _automatically_ created when you push data.
5. Update section 11 to show how Mariam searches in the AWISC and finds the data set, then uses the MQTT client to subscribe.
6. Demo slot is 25 mins but will be at end of day, so could sneak a few more mins. Aim for 5 min intro, 15 min demo, 5 min Q&A.
7. Remy can know the name of the channel to subscribe to beforehand.
8. Remy's phone could raise an alert when a message arrives.

**Comment by rogers492** [comment]
@6a6d74 The animation at the end is great - it makes the process clear.

**Comment by tg4444** [comment]
This is the cast of the video presentation
Dave:
![dave](https://user-images.githubusercontent.com/20536453/37658970-72454748-2c57-11e8-95d0-cc358bcb3323.png)

John:
![john](https://user-images.githubusercontent.com/20536453/37658972-726516d6-2c57-11e8-8333-01649030ef62.png)

Mariam:
![mariam](https://user-images.githubusercontent.com/20536453/37658973-728b8bea-2c57-11e8-89ce-bc19b1a8f991.png)

Mohamed:
![mohamed](https://user-images.githubusercontent.com/20536453/37658974-72a98dd4-2c57-11e8-9ff5-916c2ffbcce4.png)

Omar:
![omar](https://user-images.githubusercontent.com/20536453/37658976-72c872bc-2c57-11e8-80a9-8ac4d0cad545.png)

Vicky:
![vicky](https://user-images.githubusercontent.com/20536453/37658977-72e911f2-2c57-11e8-86fe-aa7da44df46c.png)

**Comment by 6a6d74** [comment]
PDF version...

[openwis-wis2-demo-cbsteco-iii.pdf](https://github.com/OpenWIS/djibouti/files/1833435/openwis-wis2-demo-cbsteco-iii.pdf)

**Comment by NMichas** [comment]
[openwis-wis2-demo-cbsteco-ii.pdf](https://github.com/OpenWIS/djibouti/files/1833442/openwis-wis2-demo-cbsteco-ii.pdf)

**Comment by rogers492** [comment]
topic name:

https://openwis2.eurodyn.com/ldsh-gaul/bib/bibracte

**Comment by 6a6d74** [comment]
updated version of the presentation ...

[openwis-wis2-demo-cbsteco-iii.pptx](https://github.com/OpenWIS/djibouti/files/1834164/openwis-wis2-demo-cbsteco-iii.pptx)

**Comment by 6a6d74** [comment]
tomorrow at the scrum:
1. run through the video
2. do a dress rehearsal for the demo

For that I will need the data file & the dataset description (for each of the four tabs) relating to Bibracte

**Comment by tg4444** [comment]
Hi all,
This is the new version of the video:
https://www.youtube.com/watch?v=Nm2Oh_jioIE&rel=0

**Comment by 6a6d74** [comment]
Looks great! Excellent work ...

(just a minor niggle ... AWISC comes out sounding like "a wisc" rather than "aye wisc" ... we can put up with that!)

**Comment by tg4444** [comment]
And here is the Bibracte-related information (not sure if you want me to create a different issue for that).

File | Description
-----|-----------------
[Bibracte-Dataset.xlsx](https://github.com/OpenWIS/djibouti/files/1837429/Bibracte-Dataset.xlsx) | This is the information required in order to fill-in the Bibracte dataset that @6a6d74 will create during the demo.
[Bibracte-csv-data.zip](https://github.com/OpenWIS/djibouti/files/1837431/Bibracte-csv-data.zip) | This zip file contains 3 csv files with data taken from NOAA readings that @solson-nws provided us. Each file contains a single measurement.

**Comment by 6a6d74** [comment]
Things we talked about at the scrum meeting during the dress rehearsal...

- [ ]  reload all the tabs before the presentation
- [x]  find a Javascript app to display CSV files ... as an illustrative example, I will use [this](https://canvasjs.com/javascript-charts/chart-image-overlay/) from canvasjs.com
- [x] improve how we cut and paste information in the demo ... actually, we've got rid of most of this in the demo now (see below) - the only bit left is for the RDSH registration and I've put these details into a separate note that I can cut and paste from
- [x] skip registration of the AWISC during the live demo - it's pretty much identical to the RDSH ... I've moved RDSH so it comes first in the running order; also, by pre-registering the AWISC (and the Bibracte dataset) we can index Gaul LDSH from the AWISC before the live demo
- [x] the lat/lon location data for Bibracte is in degrees/minutes/seconds - the application needs decimal lat/lon ... we agreed that this doesn't really matter
- [x] remove the view of the RDSH channels from the presentation & demo ... done; this doesn't really add anything
- [x] add that the download URL (download link) becomes available only once the data has been pushed to the LDSH ... done
- [x] save time by already having the Bibracte dataset configured ... presentation / demo script modified to talk through the existing configuration
- [x] skip over the "search engine metadata" tab ... done; keeping this would just create more questions
- [x] Jeremy to use net2ftp browser-based FTP client ... we checked that this worked during the scrum

**Comment by 6a6d74** [comment]
I'll reload all the browser sessions on Tuesday afternoon before the demonstration.

@tg4444 / @NMichas - the initial state for the demo should be:

- [x] Britannia LDSH is registered with AWISC & RDSH, and has some datasets configured
- [x] Gaul LDSH is already registered with AWISC
- [x] Gaul LDSH is not registered with RDSH
- [x] Bibracte dataset is already configured & indexed by AWISC
- [x] Bibracte dataset has no data

Please can you make sure that things are set up like this? Thank you.

**Comment by NMichas** [comment]
Sure, we'll have these configured for Tuesday morning.

**Comment by 6a6d74** [comment]
Hi @NMichas  

Also, please can you remove "wind speed" from the Cenabum dataset (Gaul LDSH) ... I want only to find Bibracte when I do expert search

I've done this in the live Web app - but you might restart / reload the data at some point

**Comment by 6a6d74** [comment]
@NMichas 

One more thing - just in case the [net2ftp](http://net2ftp.com/index.php) service is down during the demo, can you have an FTP client & data files ready to go? Thanks...

**Comment by 6a6d74** [comment]
Updated presentation (and notes)

It's pretty close to 15-minutes plus the video. ED team will need to get involved at the end when they play Mariam....

[openwis-wis2-demo-cbsteco-vi.pptx](https://github.com/OpenWIS/djibouti/files/1844774/openwis-wis2-demo-cbsteco-vi.pptx)

[openwis-wis2-demo-cbsteco-vi-notes.pdf](https://github.com/OpenWIS/djibouti/files/1844773/openwis-wis2-demo-cbsteco-vi-notes.pdf)

**Comment by 6a6d74** [comment]
Final (hopefully!) update to the presentation - making the summary points on a separate slide.

[openwis-wis2-demo-cbsteco-vii.pptx](https://github.com/OpenWIS/djibouti/files/1845267/openwis-wis2-demo-cbsteco-vii.pptx)

**Comment by 6a6d74** [comment]
Thinking about tomorrow's live demo, I though I would explain the logistics and running order...

I will be hosting a WebEx for the demo tomorrow. Details are:

- Tuesday, March 27, 2018 | 5:00 pm CEST (GMT+02:00) | 2 hours
- https://metoffice.webex.com/metoffice/j.php?MTID=md5d02718a5828ef8b3b83ea48a0a7e63
- Meeting number: 847 670 466 

The demo itself is due to start at 5:30 pm CEST - but please get online earlier.

I've asked Paul to send around the details by email - including the password!


1. Slides 1-17 is me, switching to the various Web pages as needed
2. Slide 18 - check with Remy that his mobile phone is configured for subscription to Bibracte dataset via MQTT
3. Slides 19-20 is me in the driving seat again
4. Slide 21: EuroDyn play the role of Mariam ... I pass the WebEx presenter mode to EuroDyn and show the WebEx screens-share ... EuroDyn then (I) show https://openwis2.eurodyn.com/awisc; (ii) type "bibracte" into the search field; (iii) click through to the Bibracte dataset page; (iv) find the <topic name>; (v) copy this into the MQTT client ... for speed, EuroDyn keep the presenter mode, but I go back to presenting the slides 
5. Slide 22-24 is me again
6. Slide 25 is the complicated one for the demo- see below 
7. Slides 26-27 is me to summarise and finish

Note: quite a few slides are hidden!

Slide 25:
1. Check that EuroDyn (Mariam) and Remy are ready to receive data
2. I switch to net2ftp.com FTP client and find a "bibracte" data set to upload
3. I show _both_ my browser and the WebEx screen share on the screen ... so that we can see when the data arrives at the MQTT client
4. I press "submit" on the FTP client
5. We _should_ see the data arrive on Mariam's MQTT client and hear data arrive on Remy's phone
6. I check with Remy that he received the data

**Comment by 6a6d74** [comment]
@NMichas - 

Have you decided who from EuroDyn will be Mariam tomorrow? 

See [above](https://github.com/OpenWIS/djibouti/issues/17#issuecomment-376182908).

**Comment by NMichas** [comment]
Dimitris Papadeas will be Mariam.

**Comment by 6a6d74** [comment]
Thanks - 

@dimipapadeas - please let me know if you have any questions about the demo. The Notes in the PowerPoint presentation should show what you need to do.

**Comment by dimipapadeas** [comment]
@6a6d74 No questions from my side, the Notes are quite clear.

**Comment by dimipapadeas** [comment]
@6a6d74, @rogers492 , @woollattd  We are ready for the Demo, LDSHs, RDSH and AWISC are set [as requested](https://github.com/OpenWIS/djibouti/issues/17#issuecomment-375855758).

**Comment by 6a6d74** [comment]
@dimipapadeas - thank you. I've been through and reloaded all my tabs :-)

I noticed that LDSH Gaul was still shown in the RDSH. I have deleted it ...

**Comment by 6a6d74** [comment]
@dimipapadeas 

My audio (on the WebEx) isn't going to be connected from the laptop I'm using ... 

So - I will dial into the WebEx on my iPhone for audio (speaker phone) ... I'll be able to talk to you through that. Hopefully we'll not get feedback from the conference audio system!

**Comment by 6a6d74** [comment]
All - for those who wish to follow the demo live, WMO are broadcasting the session live ....

"""
The Plenary discussion will be broadcasted through Web-streaming; please follow the link below for accessing it:

https://c.connectedviews.com/01/WMOPublic
"""

(see http://meetings.wmo.int/cbs-teco-2018/SitePages/Session%20Information.aspx)

**Comment by 6a6d74** [comment]
@dimipapadeas  

I should add that the WMO broadcast has about a 60-second delay, so don't rely on that for knowing when you need to be Mariam!

**Comment by tg4444** [comment]
Concerning the Google search, it has not indexed the dataset pages yet.
Furthermore, the search results for "ldsh britannia" (without quotes) are inconsistent when searching from Greece. If including the quotes, we appear as the first result.

I also tried using a Swiss proxy server to do the search (a server of the World Health Organization in Geneva), and "ldsh britannia" (without quotes) did return as the first result.

**Comment by 6a6d74** [comment]
@tg4444 - 

In the demo I talk about our WIS2 pilot application "not being popular enough yet" to be regularly indexed or to rank highly in the result. 

Then I do an alternate search for the LDSH itself. I noticed this morning that "ldsh britannia" didn't come up in the first page either ... but I found that if I mis-spelled the search as "ldsh brittania" it comes up third in the search results.

Thanks for reminding me that I can search with quoted text!

**Comment by 6a6d74** [comment]
All - just to be aware that the CBS TECO session is currently running 30-minutes early. I doubt that it will affect the start time of the demo ... but @dimipapadeas: please be ready a little early!

**Comment by 6a6d74** [comment]
Hello ... me again! The demo will now be from the Press Room at WMO rather than the main conference room; probably to make it easier to hook up my laptop etc. This means that **WMO will _not_ be broadcasting the WIS2 side event** (and our demo). 

WMO will still record the session (via BlueJeans videoconference). I will still be using WebEx as per our plan.

You folks can follow the demo via WebEx; hopefully you'll be able to hear me via my phone audio (on speaker phone) as I talk through the presentation.

**Comment by 6a6d74** [comment]
Update on side event start time! (session agenda was just updated)

Scheduled start time for the WIS 2.0 side event is now 17:00 CEST (GMT+2)

**Comment by rogers492** [comment]
Demo presented to WMO CBS TECO  Geneva at 17:00 CEST 27th March 2018.

**Comment by 6a6d74** [comment]
Hi all - other than a few errors (from me! apologies for not starting the screen share) I think it went well ... the software worked without a problem. I think that people are beginning to get the idea about what we're trying to achieve.

@dimipapadeas - thanks for being Mariam!
@remygiraud - thanks for being yourself :-)

**Comment by solson-nws** [comment]
Just a quick shout out on a job well done!

Thanks to Jeremy for spearheading this!  Thanks to the Eurodyn folks for
doing the roles, thanks to Remy for using your phone!  And thanks to the
entire team developing the story and the demo!   It's a collective effort
and your efforts were well received!

Steve

**Comment by 6a6d74** [comment]
I've cleaned up the presentation notes & removed the config details etc. See below...

I'll share this with WMO for publication on the CBS TECO meeting pages.

[openwis-wis2-demo-cbsteco-vii-clean.pptx](https://github.com/OpenWIS/djibouti/files/1852778/openwis-wis2-demo-cbsteco-vii-clean.pptx)

**Comment by 6a6d74** [comment]
Thanks @solson-nws 

I think that the video and the demo will be useful for lots of outreach type activities - trying to get the WMO community to understand how WIS 2 is different.

**Comment by 6a6d74** [comment]
PowerPoint:
[openwis-wis2-demo-cbsteco-vii-clean.pptx](https://github.com/OpenWIS/WIS2-PoC-1/files/1894878/openwis-wis2-demo-cbsteco-vii-clean.pptx)

PDF:
[openwis-wis2-demo-cbsteco-vii-clean.pdf](https://github.com/OpenWIS/WIS2-PoC-1/files/1894882/openwis-wis2-demo-cbsteco-vii-clean.pdf)

PDF (with notes): 
[openwis-wis2-demo-cbsteco-vii-clean-(notes).pdf](https://github.com/OpenWIS/WIS2-PoC-1/files/1894884/openwis-wis2-demo-cbsteco-vii-clean-.notes.pdf)
