### ISSUE TITLE
CBS TECO demo - QR code mobile app

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/djibouti#18]
By end of Friday 9-Mar-2018, check and report whether a mobile app exists that incorporates QR code and MQTT.

**Comment by dimipapadeas** [comment]
@6a6d74, @rogers492   We did an investigation and we found out that there is no mqtt client that supports mobile deep linking. (Direct app call via QR code).

Since there is no suitable app, we would prefer one of the following MQTT clients for Android OS:

MQTT Client
https://play.google.com/store/apps/details?id=in.dc297.mqttclpro

MQTT Client for Easycontrol
https://play.google.com/store/apps/details?id=info.laptrinhpic.easycontrol.mqttplugin

IoT MQTT Dashboard
https://play.google.com/store/apps/details?id=com.thn.iotmqttdashboard

**Comment by rogers492** [comment]
So am I right in thinking this rules out being able to have the audience subscribe using their own phone?

**Comment by NMichas** [comment]
They can still connect, however they'll have to type in the URL of the MQTT server.

**Comment by rogers492** [comment]
Demo ready - won't be using QR code.
